<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Gdelt.Shared</AssemblyName>
    <RootNamespace>GdeltSearchUI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ScottPlot" Version="5.1.58" />
    <PackageReference Include="SkiaSharp" Version="3.119.0" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="9.0.5" />
  </ItemGroup>

</Project>
